[[colors.indexed_colors]]
color = "#f78c6c"
index = 16

[[colors.indexed_colors]]
color = "#ff5370"
index = 17

[[colors.indexed_colors]]
color = "#444267"
index = 18

[[colors.indexed_colors]]
color = "#32374d"
index = 19

[[colors.indexed_colors]]
color = "#8796b0"
index = 20

[[colors.indexed_colors]]
color = "#959dcb"
index = 21

[colors.bright]
black = "#676e95"
blue = "#82aaff"
cyan = "#89ddff"
green = "#c3e88d"
magenta = "#c792ea"
red = "#f07178"
white = "#ffffff"
yellow = "#ffcb6b"

[colors.cursor]
cursor = "#959dcb"
text = "#292d3e"

[colors.normal]
black = "#292d3e"
blue = "#82aaff"
cyan = "#89ddff"
green = "#c3e88d"
magenta = "#c792ea"
red = "#f07178"
white = "#959dcb"
yellow = "#ffcb6b"

[colors.primary]
background = "#292d3e"
foreground = "#959dcb"
