#!/bin/sh

# The folder that will be used for trash
trash=${TRASH:-'[Gmail]/Trash'}
# The folder that will be used for archiving
archive=${ARCHIVE:-'[Gmail]/All Mail'}
# The folder that will be used for sent mail
sent=${SENT:-'[Gmail]/Sent Mail'}

# If its already in trash, remove it from the inbox
notmuch tag +deleted -inbox -- folder:"\"${trash}\""
# If its been sent, pass that on through
notmuch tag +sent -- folder:"\"${sent}\"" and not tag:sent

# If it has been deleted from an inbox, make sure we remove it from
# the IMAP folder
notmuch search --output=files tag:inbox | grep 'T$' | xargs rm -f
# If its already been archived, mark it as such
notmuch tag +archive -inbox -- folder:"\"${archive}\"" and not folder:'"/(INBOX|.*@.*)/"' and not tag:archive
# If its not in an inbox, don't mark it as "inbox"
notmuch tag -inbox -- tag:inbox and not folder:'"/(INBOX|.*@.*)/"'

# When deleting emails straight from gmail (say on mobile), then they
# get given the "trashed" IMAP flag and are copied to the trash folder.
# As such, when we see such emails, we need to make sure they are
# properly deleted.
# These emails will be retagged below
notmuch search --output=files tag:deleted and not folder:"\"${trash}\"" \
    | grep -iv "${trash_re}" \
    | while IFS= read -r file;
do
    name="${file##*/}"
    # Get the IMAP flags
    flags="${name##*:}"
    directory=${file%%/${name}}
    # If its in the "new" directory, we need to set the flags ourselves
    if [ "${directory##*/}" = "new" ]; then flags="2,"; fi
    echo "Trashing ${file}"
    mv "${file}" "${dir}/${trash}/cur/$(uuidgen):${flags%%T}"
done

# Retag things that have been deleted
notmuch tag -archive -inbox -- tag:deleted and "(tag:archive or tag:inbox)"

notmuch new --no-hooks

count=$(notmuch count tag:unread and tag:inbox)
[ "${count}" -gt 0 ] && notify-send -i /usr/share/doc/neomutt/logo/neomutt.svg "${count} new emails" || true
