#!/bin/sh
# This file does some preprocessing for notmuch by putting some special tags
# in the correct maildir directories.

# The tag and folder that will be used for trash
trash='[Gmail]/Trash'
trash_re='\[Gmail\]/Trash'

# The tag and folder that will be used for archiving
archive='[Gmail]/All Mail'
archive_re='\[Gmail\]/All Mail'

# Fix up directories with tags before we sync
dir=$(notmuch config get database.path)
mbdir=${dir##*/}

# Move it to the trash if its deleted and not already there
notmuch search --output=files tag:deleted and not folder:"\"$trash\"" \
    | grep -iv "$trash_re" \
    | while IFS= read -r file;
do
    name="${file##*/}"
    # Get the IMAP flags
    flags="${name##*:}"
    directory=${file%%/${name}}
    # If its in the "new" directory, we need to set the flags ourselves
    if [ "${directory##*/}" = "new" ]; then flags="2,"; fi
    echo "Trashing $file"
    mv "$file" "$dir/$trash/cur/$(uuidgen):${flags%%T}"
done

# Remove it from trash if its been undeleted and put it back in the archive
# This will be retagged below
notmuch search --output=files folder:"\"$trash\"" and not tag:deleted \
    | while IFS= read -r file;
do
    name="${file##*/}"
    # Get the IMAP flags
    flags="${name##*:}"
    directory=${file%%/${name}}
    # If its in the "new" directory, we need to set the flags ourselves
    if [ "${directory##*/}" = "new" ]; then flags="2,"; fi
    echo "Untrashing $file"
    mv "$file" "$dir/$archive/cur/$(uuidgen):${flags%%T}"
done

# If its not tagged inbox and is in an inbox, archive it
notmuch tag +archive -- folder:'"/(INBOX|.*@.*)/"' and not tag:inbox

# Archive things that are marked "archive"
notmuch search --output=files tag:archive and folder:'"/(INBOX|.*@.*)/"' \
    | grep -iv "$archive_re" \
    | while IFS= read -r file;
do
    name="${file##*/}"
    # Get the IMAP flags
    flags="${name##*:}"
    directory=${file%%/${name}}
    # If its in the "new" directory, we need to set the flags ourselves
    if [ "${directory##*/}" = "new" ]; then flags="2,"; fi
    echo "Archiving $file"
    # In gmail, everything is already archived in "All Mail"
    # We can prevent file duplication by just deleting the extra file in
    # whatever inbox it is.
    rm "$file"
done

# If its in All Mail and not in an inbox, tag it as archived
# One such reason why it might be this way is because of trash removal
notmuch tag +archive -inbox -- folder:"\"$archive\"" \
    and not folder:'"/(INBOX|.*@.*)/"' \
    and not tag:archive

mbsync "$mbdir"
