[env]
TERM = "tmux-256color"

[font]
size = 15

[window]
decorations = "none"
dynamic_padding = true
dynamic_title = true
option_as_alt = "OnlyLeft"

[window.padding]
x = 2
y = 2

[general]
import = ["colours/onedark.toml"]
